### ISSUE TITLE
The id parameter in getDebates call

### ISSUE THREAD

**Issue by yunjiali** [ifraixedes/node-theyworkforyou-api#1]
Firstly, thanks for your work. This library is very helpful :=)

I am not sure if this is an issue, but my question is why the id parameter is required in getDebates method in the api.ls file? I didn't see any document about that in TheyWorkForYou API. I tried to put an empty string in the getDebates call as the first parameter:

twfyClient.getDebates("",{type:"commons",date:"2013-01-07",output:"js"});

I can still get the list of debate headings. So what's the meaning of the id then? Many thanks.

**Comment by ifraixedes** [comment]
It was a bug, it required `id` rather than `type`, so I replaced it.

Thanks.

**Comment by yunjiali** [comment]
Thanks!
